In [2]:
import tensorflow as tf
import numpy as np

In [8]:
a = tf.constant(np.arange(2, 10, dtype=np.int32), shape=[2,4])
b = tf.constant(np.arange(20, 28, dtype=np.int32), shape=[4,2])

In [10]:
with tf.Session() as sess:
    print(sess.run(a))
    print()
    print(sess.run(b))
    print()
    print(sess.run(tf.matmul(b,a)))

[[2 3 4 5]
 [6 7 8 9]]

[[20 21]
 [22 23]
 [24 25]
 [26 27]]

[[166 207 248 289]
 [182 227 272 317]
 [198 247 296 345]
 [214 267 320 373]]


In [19]:
c = tf.constant(np.arange(2, 10, dtype=np.int32), shape=[2,2,2,4])
d = tf.constant(np.arange(20, 28, dtype=np.int32), shape=[2,2,4,4])

In [20]:
with tf.Session() as sess:
    print(sess.run(c))
    print()
    print(sess.run(d))
    print()
    print(sess.run(tf.matmul(c,d)))

[[[[2 3 4 5]
   [6 7 8 9]]

  [[9 9 9 9]
   [9 9 9 9]]]


 [[[9 9 9 9]
   [9 9 9 9]]

  [[9 9 9 9]
   [9 9 9 9]]]]

[[[[20 21 22 23]
   [24 25 26 27]
   [27 27 27 27]
   [27 27 27 27]]

  [[27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]]]


 [[[27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]]

  [[27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]
   [27 27 27 27]]]]

[[[[355 360 365 370]
   [747 760 773 786]]

  [[972 972 972 972]
   [972 972 972 972]]]


 [[[972 972 972 972]
   [972 972 972 972]]

  [[972 972 972 972]
   [972 972 972 972]]]]
